#!/bin/env bash

usage()
{
    echo "usage: $0 <eco|comfort|turbo>"
}

if test $UID -ne 0; then
    echo "error: this command need to be run as root" >&2
    exit 1
fi

if test $# -eq 0; then
    isw -S
    exit 0
elif test $# -ne 1; then
    usage >&2
    exit 1
fi

if test "$1" = "eco"; then
    isw -S eco
elif test "$1" = "comfort"; then
    isw -S comfort
elif test "$1" = "turbo"; then
    isw -S turbo
else
    echo "error: unrecognized value \`$1'" >&2
    echo "" >&2
    usage >&2
    exit 1
fi

exit 0
