#!/bin/env bash

usage()
{
    echo "usage: $0 <off|on|half|full>"
}

if test $UID -ne 0; then
    echo "error: this command need to be run as root" >&2
    exit 1
fi

if test $# -eq 0; then
    isw -u
    exit 0
elif test $# -ne 1; then
    usage >&2
    exit 1
fi

if test "$1" = "off"; then
    isw -u off
elif test "$1" = "on"; then
    isw -u on
elif test "$1" = "half"; then
    isw -u half
elif test "$1" = "full"; then
    isw -u full
else
    echo "error: unrecognized value \`$1'" >&2
    echo "" >&2
    usage >&2
    exit 1
fi

exit 0
